# Generated by Django 3.2.6 on 2022-01-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantillas',
            new_name='Plantilla',
        ),
    ]
